### ISSUE TITLE
Are our IDs unique enough?

### ISSUE THREAD

**Issue by ekoval** [ekoval/kolejka-api#5]
As I understand, we use internal Mongo's IDs in our models. Can we rely on them? Maybe it makes sense to use hand-made IDs (UUID?)
Ping @alexsv

**Comment by alexsv** [comment]
We can because mongoid is unique

Надіслано з iPhone

26 лют. 2017 р. о 16:28 Eugene Koval <notifications@github.com> написав(ла):
